services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gcal-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-static:/app/staticfiles
      - backend-db:/app/data
    env_file:
      - ./backend/.env
    networks:
      - gcal-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gcal-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - gcal-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  gcal-network:
    driver: bridge

volumes:
  backend-static:
  backend-db:
